## NumPy Exercises by Karthik Bhat 21BCE7737

In [1]:
#q1
!pip install numpy
import numpy as np

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [10]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [30]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [29]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [31]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [33]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [41]:
np.random.rand(1)

array([0.43621051])

In [43]:
np.random.randn(25) #randn is for normal distribution

array([ 0.47996464,  0.98488863,  1.94158168, -1.52753013, -0.97856689,
        1.04597689, -0.21892193, -0.37859516, -1.2462601 ,  0.0572439 ,
       -0.93296017, -0.6930156 ,  0.05232674,  1.16605053,  0.06754147,
        0.56150706, -0.68130107, -0.88140849,  0.32602416, -0.05659965,
       -1.09276569, -0.98752758, -0.7189926 ,  0.09871419,  0.54032438])

In [44]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

# NUMPY INDEXING AND SELECTION

In [54]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [55]:
mat[2:, 1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [57]:
mat[3][4]

20

In [61]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [63]:
mat[4]

array([21, 22, 23, 24, 25])

In [65]:
mat[3:5]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [67]:
mat.sum()

325

In [70]:
mat.std()

7.211102550927978

In [82]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])